### ISSUE TITLE
README deploy section refers to different AWS solution implementation guide

### ISSUE THREAD

**Issue by ckamps** [awslabs/aws-innovation-sandbox#10]
In the `Deploy` section of the `README.md` file, there's a reference to the AWS Instance Scheduler Implementation Guide. Presumably, the reference should be to the [AWS Innovation Sandbox Implementation Guide](https://docs.aws.amazon.com/solutions/latest/aws-innovation-sandbox/automated-deployment.html).

Perhaps the reference to the Instance Scheduled implementation guide was the result of a copy and paste from that guide's `README.md` file.

**Comment by suguiura-aws** [comment]
README updated
