### ISSUE TITLE
Invalid Email in the input parameters 

### ISSUE THREAD

**Issue by dspaxton** [awslabs/aws-innovation-sandbox#4]
When creating new accounts, i ran into this error whilst using emails for accounts with the format user+alias@domain.com since I only have access to one mailbox for my org. 

Could this be validated as an acceptable mail?

Updated: Its not the + which is the problem but appears to be when using a a domain that has more than domain.tld such as domain.co.uk

**Comment by cah88** [comment]
Raised https://github.com/awslabs/aws-innovation-sandbox/pull/7 to resolve.

**Comment by suguiura-aws** [comment]
validation regex updates as part of #7
