### ISSUE TITLE
Invalid Email in the input parameters - dash

### ISSUE THREAD

**Issue by joemcse** [awslabs/aws-innovation-sandbox#5]
Validation fails because we use - in email addresses...  example dev-someaccount-project123@company.com

Please update in the Lambda/innovation_create_account_ou.py.

**Comment by cah88** [comment]
Raised https://github.com/awslabs/aws-innovation-sandbox/pull/7 to resolve.

**Comment by fdoa** [comment]
+1

**Comment by suguiura-aws** [comment]
validation regex updates as part of #7
