### ISSUE TITLE
The private subnets in the ISSBXVPC Vpc are targeted to the same AZ

### ISSUE THREAD

**Issue by fdoa** [awslabs/aws-innovation-sandbox#8]
The private subnets in the InnovationSandboxSbxAccount/ISSBXVPC VPC are targeted to the same AZ.
The culprit seems to be related to the maxAzs=1

https://github.com/awslabs/aws-innovation-sandbox/blob/main/source/lib/InnovationSandboxSbxAccount.ts

`
const vpc_sbx = new ec2.Vpc(this, "ISSBXVPC", {
cidr: "192.168.0.0/16",
maxAzs: 1,`

**Comment by suguiura-aws** [comment]
Fixed
